name: Feature Request
description: Suggest a new feature or enhancement for liquidctl-gui
title: "[FEATURE] "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please fill out the form below.
  
  - type: textarea
    id: feature-description
    attributes:
      label: Feature Description
      description: A clear description of the feature you'd like to see
      placeholder: Describe the feature...
    validations:
      required: true
  
  - type: textarea
    id: use-case
    attributes:
      label: Use Case
      description: Describe the problem this feature would solve
      placeholder: What problem does this solve? When would you use it?
    validations:
      required: true
  
  - type: textarea
    id: proposed-solution
    attributes:
      label: Proposed Solution
      description: How do you think this should work?
      placeholder: Describe your proposed implementation...
    validations:
      required: true
  
  - type: dropdown
    id: priority
    attributes:
      label: Priority Level
      description: How critical is this feature to you?
      options:
        - Critical (required for basic usage)
        - High (significantly improves functionality)
        - Medium (useful enhancement)
        - Low (nice to have)
    validations:
      required: true
  
  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What other approaches have you thought about?
      placeholder: Describe alternative solutions or workarounds...
    validations:
      required: false
  
  - type: input
    id: device-compatibility
    attributes:
      label: Device Compatibility
      description: Would this apply to specific devices or all devices?
      placeholder: "e.g., All devices, NZXT Kraken only, etc."
    validations:
      required: false
  
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Any other context, screenshots, mockups, or examples
      placeholder: Add any other context here...
    validations:
      required: false
  
  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you be willing to help with this feature?
      options:
        - label: I can submit a pull request for this feature
        - label: I can help test this feature
        - label: I'm just requesting this feature
